config/routes.rb
Devex::Application.routes.draw do
  root to: 'homes#index'
  
  get '/sign_up', to: 'users#new', as: 'sign_up'
  get '/sign_in', to: 'sessions#new', as: 'sign_in'
  get '/sign_out', to: 'sessions#destroy', as: 'sign_out'
  scope "/admin", as: "admin" do
    get '/sign_in', to: 'sessions#new'
    get '/sign_out', to: 'sessions#destroy' 
  end
  resources :admins do
    member do
      get 'newpass',to: 'admins#new_password'
    end
    resources :posts, except: [:show, :index]
    resources :sessions, only: [:new, :create, :destroy]
  end
  resources :posts, only: [:show, :index]
  resources :admins, only: [:show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/admin/_dashboard.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1><%= I18n.translate('user.text') %></h1>
  </div>
  <div class="col-sm-6 admin-section">
    <header>
      <h1>
        <%= I18n.translate('post.text') %>
      </h1>
      <%= link_to I18n.translate('post.submit.text'), new_post_path,
                  class: 'btn btn-primary btn-xs pull-right add-post' %>
    </header>
    <%= render partial: 'admin/last_posts', locals: { user: current_user } %>
  </div>
</div>

app/views/admin/_last_posts.html.erb
<% if admin.last_posts.empty? %>
  پستی برای نمایش وجود ندارد.
<% end %>
<% admin.last_posts.each do |post| %>
  <article>
    <header>
      <h2><%= link_to post.title, post%></h2>
      <span class="buttons">
        <% unless post.published? %>
          <label class="btn btn-success btn-xs">
            <%= I18n.translate('post.not_published') %>
          </label>
        <% end %>
        <%= link_to I18n.translate('buttons.edit'), edit_admin_post_path(current_user, post),
                    class: 'btn btn-warning btn-xs' %>
        <%= link_to I18n.translate('buttons.delete'), admin_post_path(current_user, post), 
                    method: 'delete', class: 'btn btn-danger btn-xs' %>
      </span>
    </header>
    <p><%= markdown(post.digest) %></p>
  </article>
<% end %>