config/routes.rb
Devex::Application.routes.draw do
  root to: 'homes#index'
  
  get '/sign_up', to: 'users#new', as: 'sign_up'
  get '/sign_in', to: 'sessions#new', as: 'sign_in'
  get '/sign_out', to: 'sessions#destroy', as: 'sign_out'
  scope "/admin", as: "admin" do
    get '/sign_in', to: 'sessions#new'
    get '/sign_out', to: 'sessions#destroy' 
  end
  resources :admins do
    member do
      get 'newpass',to: 'admins#new_password'
    end
    resources :posts, except: [:show, :index]
    resources :sessions, only: [:new, :create, :destroy]
  end
  resources :posts, only: [:show, :index]
  resources :admins, only: [:show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Devex</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home</a></li>
      </ul>

      <!-- user menu for signed in users -->
      <% if signed_in? %>
        <%= render 'shared/search_form' %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= "#{current_user.first_name} #{current_user.last_name}" %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Dashboard' , current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', sign_out_path %></li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to I18n.translate('sign_in.text'), sign_in_path %>
        </li>
        <% end %>
      </ul><!-- end of user menu -->


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <%= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/shared/_form_errors.html.erb
<span class="help-block">
    <p><%= model.errors[key].first %></p>
</span>

app/views/shared/_messages.html.erb
<!-- Show flash messages -->
<% flash.each do |key, value| %>
  <div class="alert alert-dismissable alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Devex</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home</a></li>
      </ul>

      <!-- user menu for signed in users -->
      <% if signed_in? %>
        <%= render 'shared/search_form' %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= "#{current_user.first_name} #{current_user.last_name}" %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Profile', current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', sign_out_path %></li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to I18n.translate('sign_in.text'), sign_in_path %>
        </li>
        <% end %>
      </ul><!-- end of user menu -->


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_search_form.html.erb
<div class="search">
<%= form_tag(posts_url, method: "get") do %>
  <%= text_field_tag(:q, "", {class: "search-txt-bx",
                                  placeholder: I18n.translate('post.titleortag')}) %>
  <%= submit_tag(I18n.translate('form.search'), {class: 'search-btn'}) %>
<% end %>
</div>